// Code generated by ent, DO NOT EDIT.

package etcsyncrecord

import (
	"time"
)

const (
	// Label holds the string label denoting the etcsyncrecord type in the database.
	Label = "etc_sync_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldSyncData holds the string denoting the sync_data field in the database.
	FieldSyncData = "sync_data"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the etcsyncrecord in the database.
	Table = "etc_sync_record"
)

// Columns holds all SQL columns for etcsyncrecord fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldSyncData,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt time.Time
)
