// Code generated by ent, DO NOT EDIT.

package etcsyncrecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"myetc.lantron.ltd/m/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUsername), v))
	})
}

// SyncData applies equality check predicate on the "sync_data" field. It's identical to SyncDataEQ.
func SyncData(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSyncData), v))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUsername), v))
	})
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUsername), v))
	})
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.ETCSyncRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUsername), v...))
	})
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.ETCSyncRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUsername), v...))
	})
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUsername), v))
	})
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUsername), v))
	})
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUsername), v))
	})
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUsername), v))
	})
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldUsername), v))
	})
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldUsername), v))
	})
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldUsername), v))
	})
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldUsername), v))
	})
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldUsername), v))
	})
}

// SyncDataEQ applies the EQ predicate on the "sync_data" field.
func SyncDataEQ(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSyncData), v))
	})
}

// SyncDataNEQ applies the NEQ predicate on the "sync_data" field.
func SyncDataNEQ(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSyncData), v))
	})
}

// SyncDataIn applies the In predicate on the "sync_data" field.
func SyncDataIn(vs ...string) predicate.ETCSyncRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldSyncData), v...))
	})
}

// SyncDataNotIn applies the NotIn predicate on the "sync_data" field.
func SyncDataNotIn(vs ...string) predicate.ETCSyncRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldSyncData), v...))
	})
}

// SyncDataGT applies the GT predicate on the "sync_data" field.
func SyncDataGT(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSyncData), v))
	})
}

// SyncDataGTE applies the GTE predicate on the "sync_data" field.
func SyncDataGTE(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSyncData), v))
	})
}

// SyncDataLT applies the LT predicate on the "sync_data" field.
func SyncDataLT(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSyncData), v))
	})
}

// SyncDataLTE applies the LTE predicate on the "sync_data" field.
func SyncDataLTE(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSyncData), v))
	})
}

// SyncDataContains applies the Contains predicate on the "sync_data" field.
func SyncDataContains(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSyncData), v))
	})
}

// SyncDataHasPrefix applies the HasPrefix predicate on the "sync_data" field.
func SyncDataHasPrefix(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSyncData), v))
	})
}

// SyncDataHasSuffix applies the HasSuffix predicate on the "sync_data" field.
func SyncDataHasSuffix(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSyncData), v))
	})
}

// SyncDataEqualFold applies the EqualFold predicate on the "sync_data" field.
func SyncDataEqualFold(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSyncData), v))
	})
}

// SyncDataContainsFold applies the ContainsFold predicate on the "sync_data" field.
func SyncDataContainsFold(v string) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSyncData), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ETCSyncRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ETCSyncRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ETCSyncRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ETCSyncRecord {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ETCSyncRecord) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ETCSyncRecord) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ETCSyncRecord) predicate.ETCSyncRecord {
	return predicate.ETCSyncRecord(func(s *sql.Selector) {
		p(s.Not())
	})
}
