// Code generated by ent, DO NOT EDIT.

package etcuser

import (
	"time"
)

const (
	// Label holds the string label denoting the etcuser type in the database.
	Label = "etc_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEtcUsername holds the string denoting the etc_username field in the database.
	FieldEtcUsername = "etc_username"
	// FieldEtcPassword holds the string denoting the etc_password field in the database.
	FieldEtcPassword = "etc_password"
	// FieldPointUsername holds the string denoting the point_username field in the database.
	FieldPointUsername = "point_username"
	// FieldPointPassword holds the string denoting the point_password field in the database.
	FieldPointPassword = "point_password"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the etcuser in the database.
	Table = "user"
)

// Columns holds all SQL columns for etcuser fields.
var Columns = []string{
	FieldID,
	FieldEtcUsername,
	FieldEtcPassword,
	FieldPointUsername,
	FieldPointPassword,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt time.Time
)
