// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"myetc.lantron.ltd/m/ent/etcrecord"
	"myetc.lantron.ltd/m/ent/predicate"
)

// ETCRecordDelete is the builder for deleting a ETCRecord entity.
type ETCRecordDelete struct {
	config
	hooks    []Hook
	mutation *ETCRecordMutation
}

// Where appends a list predicates to the ETCRecordDelete builder.
func (erd *ETCRecordDelete) Where(ps ...predicate.ETCRecord) *ETCRecordDelete {
	erd.mutation.Where(ps...)
	return erd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (erd *ETCRecordDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(erd.hooks) == 0 {
		affected, err = erd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ETCRecordMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			erd.mutation = mutation
			affected, err = erd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(erd.hooks) - 1; i >= 0; i-- {
			if erd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = erd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, erd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (erd *ETCRecordDelete) ExecX(ctx context.Context) int {
	n, err := erd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (erd *ETCRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: etcrecord.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: etcrecord.FieldID,
			},
		},
	}
	if ps := erd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, erd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ETCRecordDeleteOne is the builder for deleting a single ETCRecord entity.
type ETCRecordDeleteOne struct {
	erd *ETCRecordDelete
}

// Exec executes the deletion query.
func (erdo *ETCRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := erdo.erd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{etcrecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (erdo *ETCRecordDeleteOne) ExecX(ctx context.Context) {
	erdo.erd.ExecX(ctx)
}
