// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"myetc.lantron.ltd/m/ent/etcrecord"
	"myetc.lantron.ltd/m/ent/predicate"
)

// ETCRecordQuery is the builder for querying ETCRecord entities.
type ETCRecordQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ETCRecord
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ETCRecordQuery builder.
func (erq *ETCRecordQuery) Where(ps ...predicate.ETCRecord) *ETCRecordQuery {
	erq.predicates = append(erq.predicates, ps...)
	return erq
}

// Limit adds a limit step to the query.
func (erq *ETCRecordQuery) Limit(limit int) *ETCRecordQuery {
	erq.limit = &limit
	return erq
}

// Offset adds an offset step to the query.
func (erq *ETCRecordQuery) Offset(offset int) *ETCRecordQuery {
	erq.offset = &offset
	return erq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (erq *ETCRecordQuery) Unique(unique bool) *ETCRecordQuery {
	erq.unique = &unique
	return erq
}

// Order adds an order step to the query.
func (erq *ETCRecordQuery) Order(o ...OrderFunc) *ETCRecordQuery {
	erq.order = append(erq.order, o...)
	return erq
}

// First returns the first ETCRecord entity from the query.
// Returns a *NotFoundError when no ETCRecord was found.
func (erq *ETCRecordQuery) First(ctx context.Context) (*ETCRecord, error) {
	nodes, err := erq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{etcrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (erq *ETCRecordQuery) FirstX(ctx context.Context) *ETCRecord {
	node, err := erq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ETCRecord ID from the query.
// Returns a *NotFoundError when no ETCRecord ID was found.
func (erq *ETCRecordQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = erq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{etcrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (erq *ETCRecordQuery) FirstIDX(ctx context.Context) int64 {
	id, err := erq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ETCRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ETCRecord entity is found.
// Returns a *NotFoundError when no ETCRecord entities are found.
func (erq *ETCRecordQuery) Only(ctx context.Context) (*ETCRecord, error) {
	nodes, err := erq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{etcrecord.Label}
	default:
		return nil, &NotSingularError{etcrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (erq *ETCRecordQuery) OnlyX(ctx context.Context) *ETCRecord {
	node, err := erq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ETCRecord ID in the query.
// Returns a *NotSingularError when more than one ETCRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (erq *ETCRecordQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = erq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{etcrecord.Label}
	default:
		err = &NotSingularError{etcrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (erq *ETCRecordQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := erq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ETCRecords.
func (erq *ETCRecordQuery) All(ctx context.Context) ([]*ETCRecord, error) {
	if err := erq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return erq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (erq *ETCRecordQuery) AllX(ctx context.Context) []*ETCRecord {
	nodes, err := erq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ETCRecord IDs.
func (erq *ETCRecordQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := erq.Select(etcrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (erq *ETCRecordQuery) IDsX(ctx context.Context) []int64 {
	ids, err := erq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (erq *ETCRecordQuery) Count(ctx context.Context) (int, error) {
	if err := erq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return erq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (erq *ETCRecordQuery) CountX(ctx context.Context) int {
	count, err := erq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (erq *ETCRecordQuery) Exist(ctx context.Context) (bool, error) {
	if err := erq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return erq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (erq *ETCRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := erq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ETCRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (erq *ETCRecordQuery) Clone() *ETCRecordQuery {
	if erq == nil {
		return nil
	}
	return &ETCRecordQuery{
		config:     erq.config,
		limit:      erq.limit,
		offset:     erq.offset,
		order:      append([]OrderFunc{}, erq.order...),
		predicates: append([]predicate.ETCRecord{}, erq.predicates...),
		// clone intermediate query.
		sql:    erq.sql.Clone(),
		path:   erq.path,
		unique: erq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ETCRecord.Query().
//		GroupBy(etcrecord.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (erq *ETCRecordQuery) GroupBy(field string, fields ...string) *ETCRecordGroupBy {
	grbuild := &ETCRecordGroupBy{config: erq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := erq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return erq.sqlQuery(ctx), nil
	}
	grbuild.label = etcrecord.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.ETCRecord.Query().
//		Select(etcrecord.FieldUsername).
//		Scan(ctx, &v)
func (erq *ETCRecordQuery) Select(fields ...string) *ETCRecordSelect {
	erq.fields = append(erq.fields, fields...)
	selbuild := &ETCRecordSelect{ETCRecordQuery: erq}
	selbuild.label = etcrecord.Label
	selbuild.flds, selbuild.scan = &erq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a ETCRecordSelect configured with the given aggregations.
func (erq *ETCRecordQuery) Aggregate(fns ...AggregateFunc) *ETCRecordSelect {
	return erq.Select().Aggregate(fns...)
}

func (erq *ETCRecordQuery) prepareQuery(ctx context.Context) error {
	for _, f := range erq.fields {
		if !etcrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if erq.path != nil {
		prev, err := erq.path(ctx)
		if err != nil {
			return err
		}
		erq.sql = prev
	}
	return nil
}

func (erq *ETCRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ETCRecord, error) {
	var (
		nodes = []*ETCRecord{}
		_spec = erq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ETCRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ETCRecord{config: erq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(erq.modifiers) > 0 {
		_spec.Modifiers = erq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, erq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (erq *ETCRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := erq.querySpec()
	if len(erq.modifiers) > 0 {
		_spec.Modifiers = erq.modifiers
	}
	_spec.Node.Columns = erq.fields
	if len(erq.fields) > 0 {
		_spec.Unique = erq.unique != nil && *erq.unique
	}
	return sqlgraph.CountNodes(ctx, erq.driver, _spec)
}

func (erq *ETCRecordQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := erq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (erq *ETCRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   etcrecord.Table,
			Columns: etcrecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: etcrecord.FieldID,
			},
		},
		From:   erq.sql,
		Unique: true,
	}
	if unique := erq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := erq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, etcrecord.FieldID)
		for i := range fields {
			if fields[i] != etcrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := erq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := erq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := erq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := erq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (erq *ETCRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(erq.driver.Dialect())
	t1 := builder.Table(etcrecord.Table)
	columns := erq.fields
	if len(columns) == 0 {
		columns = etcrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if erq.sql != nil {
		selector = erq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if erq.unique != nil && *erq.unique {
		selector.Distinct()
	}
	for _, m := range erq.modifiers {
		m(selector)
	}
	for _, p := range erq.predicates {
		p(selector)
	}
	for _, p := range erq.order {
		p(selector)
	}
	if offset := erq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := erq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (erq *ETCRecordQuery) Modify(modifiers ...func(s *sql.Selector)) *ETCRecordSelect {
	erq.modifiers = append(erq.modifiers, modifiers...)
	return erq.Select()
}

// ETCRecordGroupBy is the group-by builder for ETCRecord entities.
type ETCRecordGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ergb *ETCRecordGroupBy) Aggregate(fns ...AggregateFunc) *ETCRecordGroupBy {
	ergb.fns = append(ergb.fns, fns...)
	return ergb
}

// Scan applies the group-by query and scans the result into the given value.
func (ergb *ETCRecordGroupBy) Scan(ctx context.Context, v any) error {
	query, err := ergb.path(ctx)
	if err != nil {
		return err
	}
	ergb.sql = query
	return ergb.sqlScan(ctx, v)
}

func (ergb *ETCRecordGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range ergb.fields {
		if !etcrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ergb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ergb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ergb *ETCRecordGroupBy) sqlQuery() *sql.Selector {
	selector := ergb.sql.Select()
	aggregation := make([]string, 0, len(ergb.fns))
	for _, fn := range ergb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ergb.fields)+len(ergb.fns))
		for _, f := range ergb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ergb.fields...)...)
}

// ETCRecordSelect is the builder for selecting fields of ETCRecord entities.
type ETCRecordSelect struct {
	*ETCRecordQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ers *ETCRecordSelect) Aggregate(fns ...AggregateFunc) *ETCRecordSelect {
	ers.fns = append(ers.fns, fns...)
	return ers
}

// Scan applies the selector query and scans the result into the given value.
func (ers *ETCRecordSelect) Scan(ctx context.Context, v any) error {
	if err := ers.prepareQuery(ctx); err != nil {
		return err
	}
	ers.sql = ers.ETCRecordQuery.sqlQuery(ctx)
	return ers.sqlScan(ctx, v)
}

func (ers *ETCRecordSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(ers.fns))
	for _, fn := range ers.fns {
		aggregation = append(aggregation, fn(ers.sql))
	}
	switch n := len(*ers.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		ers.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		ers.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := ers.sql.Query()
	if err := ers.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ers *ETCRecordSelect) Modify(modifiers ...func(s *sql.Selector)) *ETCRecordSelect {
	ers.modifiers = append(ers.modifiers, modifiers...)
	return ers
}
