// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"myetc.lantron.ltd/m/ent/etcuser"
	"myetc.lantron.ltd/m/ent/predicate"
)

// ETCUserDelete is the builder for deleting a ETCUser entity.
type ETCUserDelete struct {
	config
	hooks    []Hook
	mutation *ETCUserMutation
}

// Where appends a list predicates to the ETCUserDelete builder.
func (eud *ETCUserDelete) Where(ps ...predicate.ETCUser) *ETCUserDelete {
	eud.mutation.Where(ps...)
	return eud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (eud *ETCUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eud.hooks) == 0 {
		affected, err = eud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ETCUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			eud.mutation = mutation
			affected, err = eud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eud.hooks) - 1; i >= 0; i-- {
			if eud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = eud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (eud *ETCUserDelete) ExecX(ctx context.Context) int {
	n, err := eud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (eud *ETCUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: etcuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: etcuser.FieldID,
			},
		},
	}
	if ps := eud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, eud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ETCUserDeleteOne is the builder for deleting a single ETCUser entity.
type ETCUserDeleteOne struct {
	eud *ETCUserDelete
}

// Exec executes the deletion query.
func (eudo *ETCUserDeleteOne) Exec(ctx context.Context) error {
	n, err := eudo.eud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{etcuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eudo *ETCUserDeleteOne) ExecX(ctx context.Context) {
	eudo.eud.ExecX(ctx)
}
