// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"myetc.lantron.ltd/m/ent/etcuser"
	"myetc.lantron.ltd/m/ent/predicate"
)

// ETCUserQuery is the builder for querying ETCUser entities.
type ETCUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ETCUser
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ETCUserQuery builder.
func (euq *ETCUserQuery) Where(ps ...predicate.ETCUser) *ETCUserQuery {
	euq.predicates = append(euq.predicates, ps...)
	return euq
}

// Limit adds a limit step to the query.
func (euq *ETCUserQuery) Limit(limit int) *ETCUserQuery {
	euq.limit = &limit
	return euq
}

// Offset adds an offset step to the query.
func (euq *ETCUserQuery) Offset(offset int) *ETCUserQuery {
	euq.offset = &offset
	return euq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (euq *ETCUserQuery) Unique(unique bool) *ETCUserQuery {
	euq.unique = &unique
	return euq
}

// Order adds an order step to the query.
func (euq *ETCUserQuery) Order(o ...OrderFunc) *ETCUserQuery {
	euq.order = append(euq.order, o...)
	return euq
}

// First returns the first ETCUser entity from the query.
// Returns a *NotFoundError when no ETCUser was found.
func (euq *ETCUserQuery) First(ctx context.Context) (*ETCUser, error) {
	nodes, err := euq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{etcuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (euq *ETCUserQuery) FirstX(ctx context.Context) *ETCUser {
	node, err := euq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ETCUser ID from the query.
// Returns a *NotFoundError when no ETCUser ID was found.
func (euq *ETCUserQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = euq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{etcuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (euq *ETCUserQuery) FirstIDX(ctx context.Context) int64 {
	id, err := euq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ETCUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ETCUser entity is found.
// Returns a *NotFoundError when no ETCUser entities are found.
func (euq *ETCUserQuery) Only(ctx context.Context) (*ETCUser, error) {
	nodes, err := euq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{etcuser.Label}
	default:
		return nil, &NotSingularError{etcuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (euq *ETCUserQuery) OnlyX(ctx context.Context) *ETCUser {
	node, err := euq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ETCUser ID in the query.
// Returns a *NotSingularError when more than one ETCUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (euq *ETCUserQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = euq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{etcuser.Label}
	default:
		err = &NotSingularError{etcuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (euq *ETCUserQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := euq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ETCUsers.
func (euq *ETCUserQuery) All(ctx context.Context) ([]*ETCUser, error) {
	if err := euq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return euq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (euq *ETCUserQuery) AllX(ctx context.Context) []*ETCUser {
	nodes, err := euq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ETCUser IDs.
func (euq *ETCUserQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := euq.Select(etcuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (euq *ETCUserQuery) IDsX(ctx context.Context) []int64 {
	ids, err := euq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (euq *ETCUserQuery) Count(ctx context.Context) (int, error) {
	if err := euq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return euq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (euq *ETCUserQuery) CountX(ctx context.Context) int {
	count, err := euq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (euq *ETCUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := euq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return euq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (euq *ETCUserQuery) ExistX(ctx context.Context) bool {
	exist, err := euq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ETCUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (euq *ETCUserQuery) Clone() *ETCUserQuery {
	if euq == nil {
		return nil
	}
	return &ETCUserQuery{
		config:     euq.config,
		limit:      euq.limit,
		offset:     euq.offset,
		order:      append([]OrderFunc{}, euq.order...),
		predicates: append([]predicate.ETCUser{}, euq.predicates...),
		// clone intermediate query.
		sql:    euq.sql.Clone(),
		path:   euq.path,
		unique: euq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EtcUsername int64 `json:"etc_username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ETCUser.Query().
//		GroupBy(etcuser.FieldEtcUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (euq *ETCUserQuery) GroupBy(field string, fields ...string) *ETCUserGroupBy {
	grbuild := &ETCUserGroupBy{config: euq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := euq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return euq.sqlQuery(ctx), nil
	}
	grbuild.label = etcuser.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EtcUsername int64 `json:"etc_username,omitempty"`
//	}
//
//	client.ETCUser.Query().
//		Select(etcuser.FieldEtcUsername).
//		Scan(ctx, &v)
func (euq *ETCUserQuery) Select(fields ...string) *ETCUserSelect {
	euq.fields = append(euq.fields, fields...)
	selbuild := &ETCUserSelect{ETCUserQuery: euq}
	selbuild.label = etcuser.Label
	selbuild.flds, selbuild.scan = &euq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a ETCUserSelect configured with the given aggregations.
func (euq *ETCUserQuery) Aggregate(fns ...AggregateFunc) *ETCUserSelect {
	return euq.Select().Aggregate(fns...)
}

func (euq *ETCUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range euq.fields {
		if !etcuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if euq.path != nil {
		prev, err := euq.path(ctx)
		if err != nil {
			return err
		}
		euq.sql = prev
	}
	return nil
}

func (euq *ETCUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ETCUser, error) {
	var (
		nodes = []*ETCUser{}
		_spec = euq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ETCUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ETCUser{config: euq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(euq.modifiers) > 0 {
		_spec.Modifiers = euq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, euq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (euq *ETCUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := euq.querySpec()
	if len(euq.modifiers) > 0 {
		_spec.Modifiers = euq.modifiers
	}
	_spec.Node.Columns = euq.fields
	if len(euq.fields) > 0 {
		_spec.Unique = euq.unique != nil && *euq.unique
	}
	return sqlgraph.CountNodes(ctx, euq.driver, _spec)
}

func (euq *ETCUserQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := euq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (euq *ETCUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   etcuser.Table,
			Columns: etcuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: etcuser.FieldID,
			},
		},
		From:   euq.sql,
		Unique: true,
	}
	if unique := euq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := euq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, etcuser.FieldID)
		for i := range fields {
			if fields[i] != etcuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := euq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := euq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := euq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := euq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (euq *ETCUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(euq.driver.Dialect())
	t1 := builder.Table(etcuser.Table)
	columns := euq.fields
	if len(columns) == 0 {
		columns = etcuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if euq.sql != nil {
		selector = euq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if euq.unique != nil && *euq.unique {
		selector.Distinct()
	}
	for _, m := range euq.modifiers {
		m(selector)
	}
	for _, p := range euq.predicates {
		p(selector)
	}
	for _, p := range euq.order {
		p(selector)
	}
	if offset := euq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := euq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (euq *ETCUserQuery) Modify(modifiers ...func(s *sql.Selector)) *ETCUserSelect {
	euq.modifiers = append(euq.modifiers, modifiers...)
	return euq.Select()
}

// ETCUserGroupBy is the group-by builder for ETCUser entities.
type ETCUserGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eugb *ETCUserGroupBy) Aggregate(fns ...AggregateFunc) *ETCUserGroupBy {
	eugb.fns = append(eugb.fns, fns...)
	return eugb
}

// Scan applies the group-by query and scans the result into the given value.
func (eugb *ETCUserGroupBy) Scan(ctx context.Context, v any) error {
	query, err := eugb.path(ctx)
	if err != nil {
		return err
	}
	eugb.sql = query
	return eugb.sqlScan(ctx, v)
}

func (eugb *ETCUserGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range eugb.fields {
		if !etcuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := eugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (eugb *ETCUserGroupBy) sqlQuery() *sql.Selector {
	selector := eugb.sql.Select()
	aggregation := make([]string, 0, len(eugb.fns))
	for _, fn := range eugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(eugb.fields)+len(eugb.fns))
		for _, f := range eugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(eugb.fields...)...)
}

// ETCUserSelect is the builder for selecting fields of ETCUser entities.
type ETCUserSelect struct {
	*ETCUserQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eus *ETCUserSelect) Aggregate(fns ...AggregateFunc) *ETCUserSelect {
	eus.fns = append(eus.fns, fns...)
	return eus
}

// Scan applies the selector query and scans the result into the given value.
func (eus *ETCUserSelect) Scan(ctx context.Context, v any) error {
	if err := eus.prepareQuery(ctx); err != nil {
		return err
	}
	eus.sql = eus.ETCUserQuery.sqlQuery(ctx)
	return eus.sqlScan(ctx, v)
}

func (eus *ETCUserSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(eus.fns))
	for _, fn := range eus.fns {
		aggregation = append(aggregation, fn(eus.sql))
	}
	switch n := len(*eus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		eus.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		eus.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := eus.sql.Query()
	if err := eus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (eus *ETCUserSelect) Modify(modifiers ...func(s *sql.Selector)) *ETCUserSelect {
	eus.modifiers = append(eus.modifiers, modifiers...)
	return eus
}
