// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"myetc.lantron.ltd/m/ent/etcrecord"
	"myetc.lantron.ltd/m/ent/etcsyncrecord"
	"myetc.lantron.ltd/m/ent/etcuser"
	"myetc.lantron.ltd/m/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	etcrecordFields := schema.ETCRecord{}.Fields()
	_ = etcrecordFields
	// etcrecordDescCreatedAt is the schema descriptor for created_at field.
	etcrecordDescCreatedAt := etcrecordFields[17].Descriptor()
	// etcrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	etcrecord.DefaultCreatedAt = etcrecordDescCreatedAt.Default.(time.Time)
	// etcrecordDescUpdatedAt is the schema descriptor for updated_at field.
	etcrecordDescUpdatedAt := etcrecordFields[18].Descriptor()
	// etcrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	etcrecord.DefaultUpdatedAt = etcrecordDescUpdatedAt.Default.(time.Time)
	etcsyncrecordFields := schema.ETCSyncRecord{}.Fields()
	_ = etcsyncrecordFields
	// etcsyncrecordDescCreatedAt is the schema descriptor for created_at field.
	etcsyncrecordDescCreatedAt := etcsyncrecordFields[3].Descriptor()
	// etcsyncrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	etcsyncrecord.DefaultCreatedAt = etcsyncrecordDescCreatedAt.Default.(time.Time)
	// etcsyncrecordDescUpdatedAt is the schema descriptor for updated_at field.
	etcsyncrecordDescUpdatedAt := etcsyncrecordFields[4].Descriptor()
	// etcsyncrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	etcsyncrecord.DefaultUpdatedAt = etcsyncrecordDescUpdatedAt.Default.(time.Time)
	etcuserFields := schema.ETCUser{}.Fields()
	_ = etcuserFields
	// etcuserDescCreatedAt is the schema descriptor for created_at field.
	etcuserDescCreatedAt := etcuserFields[5].Descriptor()
	// etcuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	etcuser.DefaultCreatedAt = etcuserDescCreatedAt.Default.(time.Time)
	// etcuserDescUpdatedAt is the schema descriptor for updated_at field.
	etcuserDescUpdatedAt := etcuserFields[6].Descriptor()
	// etcuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	etcuser.DefaultUpdatedAt = etcuserDescUpdatedAt.Default.(time.Time)
}
