// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ETCRecord is the predicate function for etcrecord builders.
type ETCRecord func(*sql.Selector)

// ETCSyncRecord is the predicate function for etcsyncrecord builders.
type ETCSyncRecord func(*sql.Selector)

// ETCUser is the predicate function for etcuser builders.
type ETCUser func(*sql.Selector)
